version: '3'
services:
  client:
    image: nginx
    container_name: cc-tracker-client
    volumes:
      - ./var/static:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
  tracker:
    build:
      context: .
      dockerfile: config/tracker/php-eio-ev.dockerfile
    container_name: cc-tracker
    image: cc-tracker
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    command: "/app/vendor/bin/aerys --config /app/src/aerys.php --debug --workers 8"
    links:
      - rabbit
#  processor:
#    build:
#      context: .
#      dockerfile: config/tracker/php-eio-ev.dockerfile
#    container_name: processor
#    image: processor
#    volumes:
#      - .:/app
#    command: "php /app/src/CC/Processor/app.php"
#    links:
#      - rabbit
#      - mysql
  rabbit:
    image: rabbitmq:management
    container_name: cc-tracker-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit.123
    ports: #4369 5671 5672 25672 15671 15672
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672" # GUI
#  mysql:
#    image: "mysql"
#    container_name: "mysql"
#    environment:
#      MYSQL_ROOT_PASSWORD: mysql.123
#      MYSQL_DATABASE: tracker
#      MYSQL_USER: tracker
#      MYSQL_PASSWORD: tracker.123
#    ports:
#      - "3306:3306"
